### ISSUE TITLE
Configurable Dashboard Filters

### ISSUE THREAD

**Issue by reyjohnson** [covenantproject/cov-healthpro-webui#7] opened 2020-05-21 03:46 UTC
Allow the user to refine what is shown on the dashboard, instead of showing everything by default.

**Comment by sencode** [comment] 2020-05-21 04:06
Duplicate of #11

**Closed by sencode** 2020-05-21 04:06 UTC
Labels: duplicate

**Comment by sencode** [comment] 2020-05-21 04:08
Issue #11 is linked to a Kanban card, so closing this one and continuing in #11
